SRC=vorlage.tex

all:
	@$(ECHO) "\t[LATEX]\t$(SRC)"
	@$(LATEX) $(LATEX_FLAGS) $(SRC) >> $(MAKELOG)
	@$(LATEX) $(LATEX_FLAGS) $(SRC) >> $(MAKELOG)
	@$(LATEX) $(LATEX_FLAGS) $(SRC) >> $(MAKELOG)

.PHONY: all

